/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserDashboardRouteImport } from './routes/user-dashboard'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ModDashboardRouteImport } from './routes/mod-dashboard'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MemberlistRouteImport } from './routes/memberlist'
import { Route as HelpRouteImport } from './routes/help'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UsersUserIdIndexRouteImport } from './routes/users/$userId/index'
import { Route as ForumForumIdIndexRouteImport } from './routes/forum/$forumId/index'
import { Route as UsersUserIdReputationRouteImport } from './routes/users/$userId/reputation'
import { Route as ForumForumIdThreadReplyRouteImport } from './routes/forum/$forumId/thread/reply'
import { Route as ForumForumIdThreadNewRouteImport } from './routes/forum/$forumId/thread/new'
import { Route as ForumForumIdThreadThreadIdRouteImport } from './routes/forum/$forumId/thread/$threadId'
import { ServerRoute as ApiUsersServerRouteImport } from './routes/api/users'
import { ServerRoute as ApiUsersUserIdServerRouteImport } from './routes/api/users.$userId'

const rootServerRouteImport = createServerRootRoute()

const UserDashboardRoute = UserDashboardRouteImport.update({
  id: '/user-dashboard',
  path: '/user-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ModDashboardRoute = ModDashboardRouteImport.update({
  id: '/mod-dashboard',
  path: '/mod-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberlistRoute = MemberlistRouteImport.update({
  id: '/memberlist',
  path: '/memberlist',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdIndexRoute = UsersUserIdIndexRouteImport.update({
  id: '/users/$userId/',
  path: '/users/$userId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumForumIdIndexRoute = ForumForumIdIndexRouteImport.update({
  id: '/forum/$forumId/',
  path: '/forum/$forumId/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdReputationRoute = UsersUserIdReputationRouteImport.update({
  id: '/users/$userId/reputation',
  path: '/users/$userId/reputation',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumForumIdThreadReplyRoute = ForumForumIdThreadReplyRouteImport.update({
  id: '/forum/$forumId/thread/reply',
  path: '/forum/$forumId/thread/reply',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumForumIdThreadNewRoute = ForumForumIdThreadNewRouteImport.update({
  id: '/forum/$forumId/thread/new',
  path: '/forum/$forumId/thread/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumForumIdThreadThreadIdRoute =
  ForumForumIdThreadThreadIdRouteImport.update({
    id: '/forum/$forumId/thread/$threadId',
    path: '/forum/$forumId/thread/$threadId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUsersServerRoute = ApiUsersServerRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiUsersUserIdServerRoute = ApiUsersUserIdServerRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ApiUsersServerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/memberlist': typeof MemberlistRoute
  '/messages': typeof MessagesRoute
  '/mod-dashboard': typeof ModDashboardRoute
  '/search': typeof SearchRoute
  '/team': typeof TeamRoute
  '/user-dashboard': typeof UserDashboardRoute
  '/admin': typeof AdminIndexRoute
  '/users/$userId/reputation': typeof UsersUserIdReputationRoute
  '/forum/$forumId': typeof ForumForumIdIndexRoute
  '/users/$userId': typeof UsersUserIdIndexRoute
  '/forum/$forumId/thread/$threadId': typeof ForumForumIdThreadThreadIdRoute
  '/forum/$forumId/thread/new': typeof ForumForumIdThreadNewRoute
  '/forum/$forumId/thread/reply': typeof ForumForumIdThreadReplyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/memberlist': typeof MemberlistRoute
  '/messages': typeof MessagesRoute
  '/mod-dashboard': typeof ModDashboardRoute
  '/search': typeof SearchRoute
  '/team': typeof TeamRoute
  '/user-dashboard': typeof UserDashboardRoute
  '/admin': typeof AdminIndexRoute
  '/users/$userId/reputation': typeof UsersUserIdReputationRoute
  '/forum/$forumId': typeof ForumForumIdIndexRoute
  '/users/$userId': typeof UsersUserIdIndexRoute
  '/forum/$forumId/thread/$threadId': typeof ForumForumIdThreadThreadIdRoute
  '/forum/$forumId/thread/new': typeof ForumForumIdThreadNewRoute
  '/forum/$forumId/thread/reply': typeof ForumForumIdThreadReplyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/memberlist': typeof MemberlistRoute
  '/messages': typeof MessagesRoute
  '/mod-dashboard': typeof ModDashboardRoute
  '/search': typeof SearchRoute
  '/team': typeof TeamRoute
  '/user-dashboard': typeof UserDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/users/$userId/reputation': typeof UsersUserIdReputationRoute
  '/forum/$forumId/': typeof ForumForumIdIndexRoute
  '/users/$userId/': typeof UsersUserIdIndexRoute
  '/forum/$forumId/thread/$threadId': typeof ForumForumIdThreadThreadIdRoute
  '/forum/$forumId/thread/new': typeof ForumForumIdThreadNewRoute
  '/forum/$forumId/thread/reply': typeof ForumForumIdThreadReplyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/help'
    | '/memberlist'
    | '/messages'
    | '/mod-dashboard'
    | '/search'
    | '/team'
    | '/user-dashboard'
    | '/admin'
    | '/users/$userId/reputation'
    | '/forum/$forumId'
    | '/users/$userId'
    | '/forum/$forumId/thread/$threadId'
    | '/forum/$forumId/thread/new'
    | '/forum/$forumId/thread/reply'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/help'
    | '/memberlist'
    | '/messages'
    | '/mod-dashboard'
    | '/search'
    | '/team'
    | '/user-dashboard'
    | '/admin'
    | '/users/$userId/reputation'
    | '/forum/$forumId'
    | '/users/$userId'
    | '/forum/$forumId/thread/$threadId'
    | '/forum/$forumId/thread/new'
    | '/forum/$forumId/thread/reply'
  id:
    | '__root__'
    | '/'
    | '/help'
    | '/memberlist'
    | '/messages'
    | '/mod-dashboard'
    | '/search'
    | '/team'
    | '/user-dashboard'
    | '/admin/'
    | '/users/$userId/reputation'
    | '/forum/$forumId/'
    | '/users/$userId/'
    | '/forum/$forumId/thread/$threadId'
    | '/forum/$forumId/thread/new'
    | '/forum/$forumId/thread/reply'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HelpRoute: typeof HelpRoute
  MemberlistRoute: typeof MemberlistRoute
  MessagesRoute: typeof MessagesRoute
  ModDashboardRoute: typeof ModDashboardRoute
  SearchRoute: typeof SearchRoute
  TeamRoute: typeof TeamRoute
  UserDashboardRoute: typeof UserDashboardRoute
  AdminIndexRoute: typeof AdminIndexRoute
  UsersUserIdReputationRoute: typeof UsersUserIdReputationRoute
  ForumForumIdIndexRoute: typeof ForumForumIdIndexRoute
  UsersUserIdIndexRoute: typeof UsersUserIdIndexRoute
  ForumForumIdThreadThreadIdRoute: typeof ForumForumIdThreadThreadIdRoute
  ForumForumIdThreadNewRoute: typeof ForumForumIdThreadNewRoute
  ForumForumIdThreadReplyRoute: typeof ForumForumIdThreadReplyRoute
}
export interface FileServerRoutesByFullPath {
  '/api/users': typeof ApiUsersServerRouteWithChildren
  '/api/users/$userId': typeof ApiUsersUserIdServerRoute
}
export interface FileServerRoutesByTo {
  '/api/users': typeof ApiUsersServerRouteWithChildren
  '/api/users/$userId': typeof ApiUsersUserIdServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/users': typeof ApiUsersServerRouteWithChildren
  '/api/users/$userId': typeof ApiUsersUserIdServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/users' | '/api/users/$userId'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/users' | '/api/users/$userId'
  id: '__root__' | '/api/users' | '/api/users/$userId'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiUsersServerRoute: typeof ApiUsersServerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-dashboard': {
      id: '/user-dashboard'
      path: '/user-dashboard'
      fullPath: '/user-dashboard'
      preLoaderRoute: typeof UserDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mod-dashboard': {
      id: '/mod-dashboard'
      path: '/mod-dashboard'
      fullPath: '/mod-dashboard'
      preLoaderRoute: typeof ModDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memberlist': {
      id: '/memberlist'
      path: '/memberlist'
      fullPath: '/memberlist'
      preLoaderRoute: typeof MemberlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId/': {
      id: '/users/$userId/'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/$forumId/': {
      id: '/forum/$forumId/'
      path: '/forum/$forumId'
      fullPath: '/forum/$forumId'
      preLoaderRoute: typeof ForumForumIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId/reputation': {
      id: '/users/$userId/reputation'
      path: '/users/$userId/reputation'
      fullPath: '/users/$userId/reputation'
      preLoaderRoute: typeof UsersUserIdReputationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/$forumId/thread/reply': {
      id: '/forum/$forumId/thread/reply'
      path: '/forum/$forumId/thread/reply'
      fullPath: '/forum/$forumId/thread/reply'
      preLoaderRoute: typeof ForumForumIdThreadReplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/$forumId/thread/new': {
      id: '/forum/$forumId/thread/new'
      path: '/forum/$forumId/thread/new'
      fullPath: '/forum/$forumId/thread/new'
      preLoaderRoute: typeof ForumForumIdThreadNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/$forumId/thread/$threadId': {
      id: '/forum/$forumId/thread/$threadId'
      path: '/forum/$forumId/thread/$threadId'
      fullPath: '/forum/$forumId/thread/$threadId'
      preLoaderRoute: typeof ForumForumIdThreadThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/users/$userId': {
      id: '/api/users/$userId'
      path: '/$userId'
      fullPath: '/api/users/$userId'
      preLoaderRoute: typeof ApiUsersUserIdServerRouteImport
      parentRoute: typeof ApiUsersServerRoute
    }
  }
}

interface ApiUsersServerRouteChildren {
  ApiUsersUserIdServerRoute: typeof ApiUsersUserIdServerRoute
}

const ApiUsersServerRouteChildren: ApiUsersServerRouteChildren = {
  ApiUsersUserIdServerRoute: ApiUsersUserIdServerRoute,
}

const ApiUsersServerRouteWithChildren = ApiUsersServerRoute._addFileChildren(
  ApiUsersServerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HelpRoute: HelpRoute,
  MemberlistRoute: MemberlistRoute,
  MessagesRoute: MessagesRoute,
  ModDashboardRoute: ModDashboardRoute,
  SearchRoute: SearchRoute,
  TeamRoute: TeamRoute,
  UserDashboardRoute: UserDashboardRoute,
  AdminIndexRoute: AdminIndexRoute,
  UsersUserIdReputationRoute: UsersUserIdReputationRoute,
  ForumForumIdIndexRoute: ForumForumIdIndexRoute,
  UsersUserIdIndexRoute: UsersUserIdIndexRoute,
  ForumForumIdThreadThreadIdRoute: ForumForumIdThreadThreadIdRoute,
  ForumForumIdThreadNewRoute: ForumForumIdThreadNewRoute,
  ForumForumIdThreadReplyRoute: ForumForumIdThreadReplyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiUsersServerRoute: ApiUsersServerRouteWithChildren,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
