/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserDashboardRouteImport } from './routes/user-dashboard'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ModDashboardRouteImport } from './routes/mod-dashboard'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MemberlistRouteImport } from './routes/memberlist'
import { Route as HelpRouteImport } from './routes/help'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UsersUsernameIndexRouteImport } from './routes/users/$username/index'
import { Route as ForumForumIdIndexRouteImport } from './routes/forum/$forumId/index'
import { Route as AdminForumsIndexRouteImport } from './routes/admin/forums/index'
import { Route as UsersUsernameReputationRouteImport } from './routes/users/$username/reputation'
import { Route as AdminForumsNewRouteImport } from './routes/admin/forums/new'
import { Route as ForumForumIdThreadReplyRouteImport } from './routes/forum/$forumId/thread/reply'
import { Route as ForumForumIdThreadNewRouteImport } from './routes/forum/$forumId/thread/new'
import { Route as ForumForumIdThreadThreadIdRouteImport } from './routes/forum/$forumId/thread/$threadId'
import { Route as ForumForumIdThreadThreadIdPostIdRouteImport } from './routes/forum/$forumId/thread/$threadId.$postId'
import { ServerRoute as ApiUsersQueryByUsernameServerRouteImport } from './routes/api/users/query/by-username'
import { ServerRoute as ApiUsersQueryByIdServerRouteImport } from './routes/api/users/query/by-id'
import { ServerRoute as ApiUsersCommandCreateServerRouteImport } from './routes/api/users/command/create'
import { ServerRoute as ApiThreadsQueryByIdServerRouteImport } from './routes/api/threads/query/by-id'
import { ServerRoute as ApiThreadsQueryByForumServerRouteImport } from './routes/api/threads/query/by-forum'
import { ServerRoute as ApiStatsQueryAllStatsServerRouteImport } from './routes/api/stats/query/all-stats'
import { ServerRoute as ApiSettingsQueryByNamesServerRouteImport } from './routes/api/settings/query/by-names'
import { ServerRoute as ApiSettingsQueryByNameServerRouteImport } from './routes/api/settings/query/by-name'
import { ServerRoute as ApiPostsQueryByThreadServerRouteImport } from './routes/api/posts/query/by-thread'
import { ServerRoute as ApiPostsQueryByIdServerRouteImport } from './routes/api/posts/query/by-id'
import { ServerRoute as ApiForumsQueryByIdServerRouteImport } from './routes/api/forums/query/by-id'
import { ServerRoute as ApiForumsQueryByCategoryServerRouteImport } from './routes/api/forums/query/by-category'
import { ServerRoute as ApiForumsCommandCreateServerRouteImport } from './routes/api/forums/command/create'

const rootServerRouteImport = createServerRootRoute()

const UserDashboardRoute = UserDashboardRouteImport.update({
  id: '/user-dashboard',
  path: '/user-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ModDashboardRoute = ModDashboardRouteImport.update({
  id: '/mod-dashboard',
  path: '/mod-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberlistRoute = MemberlistRouteImport.update({
  id: '/memberlist',
  path: '/memberlist',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUsernameIndexRoute = UsersUsernameIndexRouteImport.update({
  id: '/users/$username/',
  path: '/users/$username/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumForumIdIndexRoute = ForumForumIdIndexRouteImport.update({
  id: '/forum/$forumId/',
  path: '/forum/$forumId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminForumsIndexRoute = AdminForumsIndexRouteImport.update({
  id: '/admin/forums/',
  path: '/admin/forums/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUsernameReputationRoute = UsersUsernameReputationRouteImport.update({
  id: '/users/$username/reputation',
  path: '/users/$username/reputation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminForumsNewRoute = AdminForumsNewRouteImport.update({
  id: '/admin/forums/new',
  path: '/admin/forums/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumForumIdThreadReplyRoute = ForumForumIdThreadReplyRouteImport.update({
  id: '/forum/$forumId/thread/reply',
  path: '/forum/$forumId/thread/reply',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumForumIdThreadNewRoute = ForumForumIdThreadNewRouteImport.update({
  id: '/forum/$forumId/thread/new',
  path: '/forum/$forumId/thread/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumForumIdThreadThreadIdRoute =
  ForumForumIdThreadThreadIdRouteImport.update({
    id: '/forum/$forumId/thread/$threadId',
    path: '/forum/$forumId/thread/$threadId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ForumForumIdThreadThreadIdPostIdRoute =
  ForumForumIdThreadThreadIdPostIdRouteImport.update({
    id: '/$postId',
    path: '/$postId',
    getParentRoute: () => ForumForumIdThreadThreadIdRoute,
  } as any)
const ApiUsersQueryByUsernameServerRoute =
  ApiUsersQueryByUsernameServerRouteImport.update({
    id: '/api/users/query/by-username',
    path: '/api/users/query/by-username',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiUsersQueryByIdServerRoute = ApiUsersQueryByIdServerRouteImport.update({
  id: '/api/users/query/by-id',
  path: '/api/users/query/by-id',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiUsersCommandCreateServerRoute =
  ApiUsersCommandCreateServerRouteImport.update({
    id: '/api/users/command/create',
    path: '/api/users/command/create',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiThreadsQueryByIdServerRoute =
  ApiThreadsQueryByIdServerRouteImport.update({
    id: '/api/threads/query/by-id',
    path: '/api/threads/query/by-id',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiThreadsQueryByForumServerRoute =
  ApiThreadsQueryByForumServerRouteImport.update({
    id: '/api/threads/query/by-forum',
    path: '/api/threads/query/by-forum',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiStatsQueryAllStatsServerRoute =
  ApiStatsQueryAllStatsServerRouteImport.update({
    id: '/api/stats/query/all-stats',
    path: '/api/stats/query/all-stats',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiSettingsQueryByNamesServerRoute =
  ApiSettingsQueryByNamesServerRouteImport.update({
    id: '/api/settings/query/by-names',
    path: '/api/settings/query/by-names',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiSettingsQueryByNameServerRoute =
  ApiSettingsQueryByNameServerRouteImport.update({
    id: '/api/settings/query/by-name',
    path: '/api/settings/query/by-name',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiPostsQueryByThreadServerRoute =
  ApiPostsQueryByThreadServerRouteImport.update({
    id: '/api/posts/query/by-thread',
    path: '/api/posts/query/by-thread',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiPostsQueryByIdServerRoute = ApiPostsQueryByIdServerRouteImport.update({
  id: '/api/posts/query/by-id',
  path: '/api/posts/query/by-id',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiForumsQueryByIdServerRoute =
  ApiForumsQueryByIdServerRouteImport.update({
    id: '/api/forums/query/by-id',
    path: '/api/forums/query/by-id',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiForumsQueryByCategoryServerRoute =
  ApiForumsQueryByCategoryServerRouteImport.update({
    id: '/api/forums/query/by-category',
    path: '/api/forums/query/by-category',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiForumsCommandCreateServerRoute =
  ApiForumsCommandCreateServerRouteImport.update({
    id: '/api/forums/command/create',
    path: '/api/forums/command/create',
    getParentRoute: () => rootServerRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/memberlist': typeof MemberlistRoute
  '/messages': typeof MessagesRoute
  '/mod-dashboard': typeof ModDashboardRoute
  '/report': typeof ReportRoute
  '/search': typeof SearchRoute
  '/team': typeof TeamRoute
  '/user-dashboard': typeof UserDashboardRoute
  '/admin': typeof AdminIndexRoute
  '/admin/forums/new': typeof AdminForumsNewRoute
  '/users/$username/reputation': typeof UsersUsernameReputationRoute
  '/admin/forums': typeof AdminForumsIndexRoute
  '/forum/$forumId': typeof ForumForumIdIndexRoute
  '/users/$username': typeof UsersUsernameIndexRoute
  '/forum/$forumId/thread/$threadId': typeof ForumForumIdThreadThreadIdRouteWithChildren
  '/forum/$forumId/thread/new': typeof ForumForumIdThreadNewRoute
  '/forum/$forumId/thread/reply': typeof ForumForumIdThreadReplyRoute
  '/forum/$forumId/thread/$threadId/$postId': typeof ForumForumIdThreadThreadIdPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/memberlist': typeof MemberlistRoute
  '/messages': typeof MessagesRoute
  '/mod-dashboard': typeof ModDashboardRoute
  '/report': typeof ReportRoute
  '/search': typeof SearchRoute
  '/team': typeof TeamRoute
  '/user-dashboard': typeof UserDashboardRoute
  '/admin': typeof AdminIndexRoute
  '/admin/forums/new': typeof AdminForumsNewRoute
  '/users/$username/reputation': typeof UsersUsernameReputationRoute
  '/admin/forums': typeof AdminForumsIndexRoute
  '/forum/$forumId': typeof ForumForumIdIndexRoute
  '/users/$username': typeof UsersUsernameIndexRoute
  '/forum/$forumId/thread/$threadId': typeof ForumForumIdThreadThreadIdRouteWithChildren
  '/forum/$forumId/thread/new': typeof ForumForumIdThreadNewRoute
  '/forum/$forumId/thread/reply': typeof ForumForumIdThreadReplyRoute
  '/forum/$forumId/thread/$threadId/$postId': typeof ForumForumIdThreadThreadIdPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/memberlist': typeof MemberlistRoute
  '/messages': typeof MessagesRoute
  '/mod-dashboard': typeof ModDashboardRoute
  '/report': typeof ReportRoute
  '/search': typeof SearchRoute
  '/team': typeof TeamRoute
  '/user-dashboard': typeof UserDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/forums/new': typeof AdminForumsNewRoute
  '/users/$username/reputation': typeof UsersUsernameReputationRoute
  '/admin/forums/': typeof AdminForumsIndexRoute
  '/forum/$forumId/': typeof ForumForumIdIndexRoute
  '/users/$username/': typeof UsersUsernameIndexRoute
  '/forum/$forumId/thread/$threadId': typeof ForumForumIdThreadThreadIdRouteWithChildren
  '/forum/$forumId/thread/new': typeof ForumForumIdThreadNewRoute
  '/forum/$forumId/thread/reply': typeof ForumForumIdThreadReplyRoute
  '/forum/$forumId/thread/$threadId/$postId': typeof ForumForumIdThreadThreadIdPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/help'
    | '/memberlist'
    | '/messages'
    | '/mod-dashboard'
    | '/report'
    | '/search'
    | '/team'
    | '/user-dashboard'
    | '/admin'
    | '/admin/forums/new'
    | '/users/$username/reputation'
    | '/admin/forums'
    | '/forum/$forumId'
    | '/users/$username'
    | '/forum/$forumId/thread/$threadId'
    | '/forum/$forumId/thread/new'
    | '/forum/$forumId/thread/reply'
    | '/forum/$forumId/thread/$threadId/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/help'
    | '/memberlist'
    | '/messages'
    | '/mod-dashboard'
    | '/report'
    | '/search'
    | '/team'
    | '/user-dashboard'
    | '/admin'
    | '/admin/forums/new'
    | '/users/$username/reputation'
    | '/admin/forums'
    | '/forum/$forumId'
    | '/users/$username'
    | '/forum/$forumId/thread/$threadId'
    | '/forum/$forumId/thread/new'
    | '/forum/$forumId/thread/reply'
    | '/forum/$forumId/thread/$threadId/$postId'
  id:
    | '__root__'
    | '/'
    | '/help'
    | '/memberlist'
    | '/messages'
    | '/mod-dashboard'
    | '/report'
    | '/search'
    | '/team'
    | '/user-dashboard'
    | '/admin/'
    | '/admin/forums/new'
    | '/users/$username/reputation'
    | '/admin/forums/'
    | '/forum/$forumId/'
    | '/users/$username/'
    | '/forum/$forumId/thread/$threadId'
    | '/forum/$forumId/thread/new'
    | '/forum/$forumId/thread/reply'
    | '/forum/$forumId/thread/$threadId/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HelpRoute: typeof HelpRoute
  MemberlistRoute: typeof MemberlistRoute
  MessagesRoute: typeof MessagesRoute
  ModDashboardRoute: typeof ModDashboardRoute
  ReportRoute: typeof ReportRoute
  SearchRoute: typeof SearchRoute
  TeamRoute: typeof TeamRoute
  UserDashboardRoute: typeof UserDashboardRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminForumsNewRoute: typeof AdminForumsNewRoute
  UsersUsernameReputationRoute: typeof UsersUsernameReputationRoute
  AdminForumsIndexRoute: typeof AdminForumsIndexRoute
  ForumForumIdIndexRoute: typeof ForumForumIdIndexRoute
  UsersUsernameIndexRoute: typeof UsersUsernameIndexRoute
  ForumForumIdThreadThreadIdRoute: typeof ForumForumIdThreadThreadIdRouteWithChildren
  ForumForumIdThreadNewRoute: typeof ForumForumIdThreadNewRoute
  ForumForumIdThreadReplyRoute: typeof ForumForumIdThreadReplyRoute
}
export interface FileServerRoutesByFullPath {
  '/api/forums/command/create': typeof ApiForumsCommandCreateServerRoute
  '/api/forums/query/by-category': typeof ApiForumsQueryByCategoryServerRoute
  '/api/forums/query/by-id': typeof ApiForumsQueryByIdServerRoute
  '/api/posts/query/by-id': typeof ApiPostsQueryByIdServerRoute
  '/api/posts/query/by-thread': typeof ApiPostsQueryByThreadServerRoute
  '/api/settings/query/by-name': typeof ApiSettingsQueryByNameServerRoute
  '/api/settings/query/by-names': typeof ApiSettingsQueryByNamesServerRoute
  '/api/stats/query/all-stats': typeof ApiStatsQueryAllStatsServerRoute
  '/api/threads/query/by-forum': typeof ApiThreadsQueryByForumServerRoute
  '/api/threads/query/by-id': typeof ApiThreadsQueryByIdServerRoute
  '/api/users/command/create': typeof ApiUsersCommandCreateServerRoute
  '/api/users/query/by-id': typeof ApiUsersQueryByIdServerRoute
  '/api/users/query/by-username': typeof ApiUsersQueryByUsernameServerRoute
}
export interface FileServerRoutesByTo {
  '/api/forums/command/create': typeof ApiForumsCommandCreateServerRoute
  '/api/forums/query/by-category': typeof ApiForumsQueryByCategoryServerRoute
  '/api/forums/query/by-id': typeof ApiForumsQueryByIdServerRoute
  '/api/posts/query/by-id': typeof ApiPostsQueryByIdServerRoute
  '/api/posts/query/by-thread': typeof ApiPostsQueryByThreadServerRoute
  '/api/settings/query/by-name': typeof ApiSettingsQueryByNameServerRoute
  '/api/settings/query/by-names': typeof ApiSettingsQueryByNamesServerRoute
  '/api/stats/query/all-stats': typeof ApiStatsQueryAllStatsServerRoute
  '/api/threads/query/by-forum': typeof ApiThreadsQueryByForumServerRoute
  '/api/threads/query/by-id': typeof ApiThreadsQueryByIdServerRoute
  '/api/users/command/create': typeof ApiUsersCommandCreateServerRoute
  '/api/users/query/by-id': typeof ApiUsersQueryByIdServerRoute
  '/api/users/query/by-username': typeof ApiUsersQueryByUsernameServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/forums/command/create': typeof ApiForumsCommandCreateServerRoute
  '/api/forums/query/by-category': typeof ApiForumsQueryByCategoryServerRoute
  '/api/forums/query/by-id': typeof ApiForumsQueryByIdServerRoute
  '/api/posts/query/by-id': typeof ApiPostsQueryByIdServerRoute
  '/api/posts/query/by-thread': typeof ApiPostsQueryByThreadServerRoute
  '/api/settings/query/by-name': typeof ApiSettingsQueryByNameServerRoute
  '/api/settings/query/by-names': typeof ApiSettingsQueryByNamesServerRoute
  '/api/stats/query/all-stats': typeof ApiStatsQueryAllStatsServerRoute
  '/api/threads/query/by-forum': typeof ApiThreadsQueryByForumServerRoute
  '/api/threads/query/by-id': typeof ApiThreadsQueryByIdServerRoute
  '/api/users/command/create': typeof ApiUsersCommandCreateServerRoute
  '/api/users/query/by-id': typeof ApiUsersQueryByIdServerRoute
  '/api/users/query/by-username': typeof ApiUsersQueryByUsernameServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths:
    | '/api/forums/command/create'
    | '/api/forums/query/by-category'
    | '/api/forums/query/by-id'
    | '/api/posts/query/by-id'
    | '/api/posts/query/by-thread'
    | '/api/settings/query/by-name'
    | '/api/settings/query/by-names'
    | '/api/stats/query/all-stats'
    | '/api/threads/query/by-forum'
    | '/api/threads/query/by-id'
    | '/api/users/command/create'
    | '/api/users/query/by-id'
    | '/api/users/query/by-username'
  fileServerRoutesByTo: FileServerRoutesByTo
  to:
    | '/api/forums/command/create'
    | '/api/forums/query/by-category'
    | '/api/forums/query/by-id'
    | '/api/posts/query/by-id'
    | '/api/posts/query/by-thread'
    | '/api/settings/query/by-name'
    | '/api/settings/query/by-names'
    | '/api/stats/query/all-stats'
    | '/api/threads/query/by-forum'
    | '/api/threads/query/by-id'
    | '/api/users/command/create'
    | '/api/users/query/by-id'
    | '/api/users/query/by-username'
  id:
    | '__root__'
    | '/api/forums/command/create'
    | '/api/forums/query/by-category'
    | '/api/forums/query/by-id'
    | '/api/posts/query/by-id'
    | '/api/posts/query/by-thread'
    | '/api/settings/query/by-name'
    | '/api/settings/query/by-names'
    | '/api/stats/query/all-stats'
    | '/api/threads/query/by-forum'
    | '/api/threads/query/by-id'
    | '/api/users/command/create'
    | '/api/users/query/by-id'
    | '/api/users/query/by-username'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiForumsCommandCreateServerRoute: typeof ApiForumsCommandCreateServerRoute
  ApiForumsQueryByCategoryServerRoute: typeof ApiForumsQueryByCategoryServerRoute
  ApiForumsQueryByIdServerRoute: typeof ApiForumsQueryByIdServerRoute
  ApiPostsQueryByIdServerRoute: typeof ApiPostsQueryByIdServerRoute
  ApiPostsQueryByThreadServerRoute: typeof ApiPostsQueryByThreadServerRoute
  ApiSettingsQueryByNameServerRoute: typeof ApiSettingsQueryByNameServerRoute
  ApiSettingsQueryByNamesServerRoute: typeof ApiSettingsQueryByNamesServerRoute
  ApiStatsQueryAllStatsServerRoute: typeof ApiStatsQueryAllStatsServerRoute
  ApiThreadsQueryByForumServerRoute: typeof ApiThreadsQueryByForumServerRoute
  ApiThreadsQueryByIdServerRoute: typeof ApiThreadsQueryByIdServerRoute
  ApiUsersCommandCreateServerRoute: typeof ApiUsersCommandCreateServerRoute
  ApiUsersQueryByIdServerRoute: typeof ApiUsersQueryByIdServerRoute
  ApiUsersQueryByUsernameServerRoute: typeof ApiUsersQueryByUsernameServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-dashboard': {
      id: '/user-dashboard'
      path: '/user-dashboard'
      fullPath: '/user-dashboard'
      preLoaderRoute: typeof UserDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mod-dashboard': {
      id: '/mod-dashboard'
      path: '/mod-dashboard'
      fullPath: '/mod-dashboard'
      preLoaderRoute: typeof ModDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memberlist': {
      id: '/memberlist'
      path: '/memberlist'
      fullPath: '/memberlist'
      preLoaderRoute: typeof MemberlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$username/': {
      id: '/users/$username/'
      path: '/users/$username'
      fullPath: '/users/$username'
      preLoaderRoute: typeof UsersUsernameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/$forumId/': {
      id: '/forum/$forumId/'
      path: '/forum/$forumId'
      fullPath: '/forum/$forumId'
      preLoaderRoute: typeof ForumForumIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/forums/': {
      id: '/admin/forums/'
      path: '/admin/forums'
      fullPath: '/admin/forums'
      preLoaderRoute: typeof AdminForumsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$username/reputation': {
      id: '/users/$username/reputation'
      path: '/users/$username/reputation'
      fullPath: '/users/$username/reputation'
      preLoaderRoute: typeof UsersUsernameReputationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/forums/new': {
      id: '/admin/forums/new'
      path: '/admin/forums/new'
      fullPath: '/admin/forums/new'
      preLoaderRoute: typeof AdminForumsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/$forumId/thread/reply': {
      id: '/forum/$forumId/thread/reply'
      path: '/forum/$forumId/thread/reply'
      fullPath: '/forum/$forumId/thread/reply'
      preLoaderRoute: typeof ForumForumIdThreadReplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/$forumId/thread/new': {
      id: '/forum/$forumId/thread/new'
      path: '/forum/$forumId/thread/new'
      fullPath: '/forum/$forumId/thread/new'
      preLoaderRoute: typeof ForumForumIdThreadNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/$forumId/thread/$threadId': {
      id: '/forum/$forumId/thread/$threadId'
      path: '/forum/$forumId/thread/$threadId'
      fullPath: '/forum/$forumId/thread/$threadId'
      preLoaderRoute: typeof ForumForumIdThreadThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/$forumId/thread/$threadId/$postId': {
      id: '/forum/$forumId/thread/$threadId/$postId'
      path: '/$postId'
      fullPath: '/forum/$forumId/thread/$threadId/$postId'
      preLoaderRoute: typeof ForumForumIdThreadThreadIdPostIdRouteImport
      parentRoute: typeof ForumForumIdThreadThreadIdRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/users/query/by-username': {
      id: '/api/users/query/by-username'
      path: '/api/users/query/by-username'
      fullPath: '/api/users/query/by-username'
      preLoaderRoute: typeof ApiUsersQueryByUsernameServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/users/query/by-id': {
      id: '/api/users/query/by-id'
      path: '/api/users/query/by-id'
      fullPath: '/api/users/query/by-id'
      preLoaderRoute: typeof ApiUsersQueryByIdServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/users/command/create': {
      id: '/api/users/command/create'
      path: '/api/users/command/create'
      fullPath: '/api/users/command/create'
      preLoaderRoute: typeof ApiUsersCommandCreateServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/threads/query/by-id': {
      id: '/api/threads/query/by-id'
      path: '/api/threads/query/by-id'
      fullPath: '/api/threads/query/by-id'
      preLoaderRoute: typeof ApiThreadsQueryByIdServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/threads/query/by-forum': {
      id: '/api/threads/query/by-forum'
      path: '/api/threads/query/by-forum'
      fullPath: '/api/threads/query/by-forum'
      preLoaderRoute: typeof ApiThreadsQueryByForumServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/stats/query/all-stats': {
      id: '/api/stats/query/all-stats'
      path: '/api/stats/query/all-stats'
      fullPath: '/api/stats/query/all-stats'
      preLoaderRoute: typeof ApiStatsQueryAllStatsServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/settings/query/by-names': {
      id: '/api/settings/query/by-names'
      path: '/api/settings/query/by-names'
      fullPath: '/api/settings/query/by-names'
      preLoaderRoute: typeof ApiSettingsQueryByNamesServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/settings/query/by-name': {
      id: '/api/settings/query/by-name'
      path: '/api/settings/query/by-name'
      fullPath: '/api/settings/query/by-name'
      preLoaderRoute: typeof ApiSettingsQueryByNameServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/posts/query/by-thread': {
      id: '/api/posts/query/by-thread'
      path: '/api/posts/query/by-thread'
      fullPath: '/api/posts/query/by-thread'
      preLoaderRoute: typeof ApiPostsQueryByThreadServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/posts/query/by-id': {
      id: '/api/posts/query/by-id'
      path: '/api/posts/query/by-id'
      fullPath: '/api/posts/query/by-id'
      preLoaderRoute: typeof ApiPostsQueryByIdServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/forums/query/by-id': {
      id: '/api/forums/query/by-id'
      path: '/api/forums/query/by-id'
      fullPath: '/api/forums/query/by-id'
      preLoaderRoute: typeof ApiForumsQueryByIdServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/forums/query/by-category': {
      id: '/api/forums/query/by-category'
      path: '/api/forums/query/by-category'
      fullPath: '/api/forums/query/by-category'
      preLoaderRoute: typeof ApiForumsQueryByCategoryServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/forums/command/create': {
      id: '/api/forums/command/create'
      path: '/api/forums/command/create'
      fullPath: '/api/forums/command/create'
      preLoaderRoute: typeof ApiForumsCommandCreateServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface ForumForumIdThreadThreadIdRouteChildren {
  ForumForumIdThreadThreadIdPostIdRoute: typeof ForumForumIdThreadThreadIdPostIdRoute
}

const ForumForumIdThreadThreadIdRouteChildren: ForumForumIdThreadThreadIdRouteChildren =
  {
    ForumForumIdThreadThreadIdPostIdRoute:
      ForumForumIdThreadThreadIdPostIdRoute,
  }

const ForumForumIdThreadThreadIdRouteWithChildren =
  ForumForumIdThreadThreadIdRoute._addFileChildren(
    ForumForumIdThreadThreadIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HelpRoute: HelpRoute,
  MemberlistRoute: MemberlistRoute,
  MessagesRoute: MessagesRoute,
  ModDashboardRoute: ModDashboardRoute,
  ReportRoute: ReportRoute,
  SearchRoute: SearchRoute,
  TeamRoute: TeamRoute,
  UserDashboardRoute: UserDashboardRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminForumsNewRoute: AdminForumsNewRoute,
  UsersUsernameReputationRoute: UsersUsernameReputationRoute,
  AdminForumsIndexRoute: AdminForumsIndexRoute,
  ForumForumIdIndexRoute: ForumForumIdIndexRoute,
  UsersUsernameIndexRoute: UsersUsernameIndexRoute,
  ForumForumIdThreadThreadIdRoute: ForumForumIdThreadThreadIdRouteWithChildren,
  ForumForumIdThreadNewRoute: ForumForumIdThreadNewRoute,
  ForumForumIdThreadReplyRoute: ForumForumIdThreadReplyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiForumsCommandCreateServerRoute: ApiForumsCommandCreateServerRoute,
  ApiForumsQueryByCategoryServerRoute: ApiForumsQueryByCategoryServerRoute,
  ApiForumsQueryByIdServerRoute: ApiForumsQueryByIdServerRoute,
  ApiPostsQueryByIdServerRoute: ApiPostsQueryByIdServerRoute,
  ApiPostsQueryByThreadServerRoute: ApiPostsQueryByThreadServerRoute,
  ApiSettingsQueryByNameServerRoute: ApiSettingsQueryByNameServerRoute,
  ApiSettingsQueryByNamesServerRoute: ApiSettingsQueryByNamesServerRoute,
  ApiStatsQueryAllStatsServerRoute: ApiStatsQueryAllStatsServerRoute,
  ApiThreadsQueryByForumServerRoute: ApiThreadsQueryByForumServerRoute,
  ApiThreadsQueryByIdServerRoute: ApiThreadsQueryByIdServerRoute,
  ApiUsersCommandCreateServerRoute: ApiUsersCommandCreateServerRoute,
  ApiUsersQueryByIdServerRoute: ApiUsersQueryByIdServerRoute,
  ApiUsersQueryByUsernameServerRoute: ApiUsersQueryByUsernameServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
