import { Thread } from "../domain/models";

const threads = [
  {
    id: 1,
    forumId: 2,
    subject: "First Thread",
    prefix: "",
    icon: "",
    pollId: null,
    userId: "uuid",
    username: "Elegant Totality",
    createdAt: new Date(),
    updatedAt: new Date(),
    firstPostId: 1,
    lastPostCreatedAt: new Date(),
    lastPosterUsername: "Elegant Totality",
    lastPosterId: "uuid",
    views: 135,
    replies: 65,
    isClosed: false,
    isSticky: false,
    ratingsNumber: 540,
    ratingsTotal: 2478,
    moderatorNotes: "",
    isDraft: false,
    isApproved: true,
    unapprovedPostsTotal: 0,
    attachmentTotal: 0,
    isDeleted: false,
  },
  {
    id: 2,
    forumId: 2,
    subject: "Single Topic",
    prefix: "",
    icon: "",
    pollId: null,
    userId: "uuid",
    username: "Elegant Totality",
    createdAt: new Date(),
    updatedAt: new Date(),
    firstPostId: 1,
    lastPostCreatedAt: new Date(),
    lastPosterUsername: "Elegant Totality",
    lastPosterId: "uuid",
    views: 33,
    replies: 1,
    isClosed: false,
    isSticky: false,
    ratingsNumber: 2,
    ratingsTotal: 9,
    moderatorNotes: "",
    isDraft: false,
    isApproved: true,
    unapprovedPostsTotal: 0,
    attachmentTotal: 0,
    isDeleted: false,
  },
  {
    id: 3,
    forumId: 2,
    subject: "Single Topic",
    prefix: "",
    icon: "",
    pollId: null,
    userId: "uuid",
    username: "Elegant Totality",
    createdAt: new Date(),
    updatedAt: new Date(),
    firstPostId: 1,
    lastPostCreatedAt: new Date(),
    lastPosterUsername: "Elegant Totality",
    lastPosterId: "uuid",
    views: 126,
    replies: 7,
    isClosed: false,
    isSticky: false,
    ratingsNumber: 3,
    ratingsTotal: 15,
    moderatorNotes: "",
    isDraft: false,
    isApproved: true,
    unapprovedPostsTotal: 0,
    attachmentTotal: 0,
    isDeleted: false,
  },
  {
    id: 4,
    forumId: 2,
    subject: "Single Topic",
    prefix: "",
    icon: "",
    pollId: null,
    userId: "uuid",
    username: "Elegant Totality",
    createdAt: new Date(),
    updatedAt: new Date(),
    firstPostId: 1,
    lastPostCreatedAt: new Date(),
    lastPosterUsername: "Elegant Totality",
    lastPosterId: "uuid",
    views: 100,
    replies: 35,
    isClosed: false,
    isSticky: false,
    ratingsNumber: 540,
    ratingsTotal: 2478,
    moderatorNotes: "",
    isDraft: false,
    isApproved: true,
    unapprovedPostsTotal: 0,
    attachmentTotal: 0,
    isDeleted: false,
  },
  {
    id: 5,
    forumId: 2,
    subject: "Single Topic",
    prefix: "",
    icon: "",
    pollId: null,
    userId: "uuid",
    username: "Elegant Totality",
    createdAt: new Date(),
    updatedAt: new Date(),
    firstPostId: 1,
    lastPostCreatedAt: new Date(),
    lastPosterUsername: "Elegant Totality",
    lastPosterId: "uuid",
    views: 100,
    replies: 35,
    isClosed: false,
    isSticky: false,
    ratingsNumber: 540,
    ratingsTotal: 2478,
    moderatorNotes: "",
    isDraft: false,
    isApproved: true,
    unapprovedPostsTotal: 0,
    attachmentTotal: 0,
    isDeleted: false,
  },
  {
    id: 6,
    forumId: 2,
    subject: "Single Topic",
    prefix: "",
    icon: "",
    pollId: null,
    userId: "uuid",
    username: "Elegant Totality",
    createdAt: new Date(),
    updatedAt: new Date(),
    firstPostId: 1,
    lastPostCreatedAt: new Date(),
    lastPosterUsername: "Elegant Totality",
    lastPosterId: "uuid",
    views: 100,
    replies: 35,
    isClosed: false,
    isSticky: false,
    ratingsNumber: 540,
    ratingsTotal: 2478,
    moderatorNotes: "",
    isDraft: false,
    isApproved: true,
    unapprovedPostsTotal: 0,
    attachmentTotal: 0,
    isDeleted: false,
  },
  {
    id: 7,
    forumId: 2,
    subject: "Single Topic",
    prefix: "",
    icon: "",
    pollId: null,
    userId: "uuid",
    username: "Elegant Totality",
    createdAt: new Date(),
    updatedAt: new Date(),
    firstPostId: 1,
    lastPostCreatedAt: new Date(),
    lastPosterUsername: "Elegant Totality",
    lastPosterId: "uuid",
    views: 100,
    replies: 35,
    isClosed: false,
    isSticky: false,
    ratingsNumber: 540,
    ratingsTotal: 2478,
    moderatorNotes: "",
    isDraft: false,
    isApproved: true,
    unapprovedPostsTotal: 0,
    attachmentTotal: 0,
    isDeleted: false,
  },
  {
    id: 8,
    forumId: 2,
    subject: "Single Topic",
    prefix: "",
    icon: "",
    pollId: null,
    userId: "uuid",
    username: "Elegant Totality",
    createdAt: new Date(),
    updatedAt: new Date(),
    firstPostId: 1,
    lastPostCreatedAt: new Date(),
    lastPosterUsername: "Elegant Totality",
    lastPosterId: "uuid",
    views: 100,
    replies: 35,
    isClosed: false,
    isSticky: false,
    ratingsNumber: 540,
    ratingsTotal: 2478,
    moderatorNotes: "",
    isDraft: false,
    isApproved: true,
    unapprovedPostsTotal: 0,
    attachmentTotal: 0,
    isDeleted: false,
  },
  {
    id: 9,
    forumId: 2,
    subject: "Single Topic",
    prefix: "",
    icon: "",
    pollId: null,
    userId: "uuid",
    username: "Elegant Totality",
    createdAt: new Date(),
    updatedAt: new Date(),
    firstPostId: 1,
    lastPostCreatedAt: new Date(),
    lastPosterUsername: "Elegant Totality",
    lastPosterId: "uuid",
    views: 100,
    replies: 35,
    isClosed: false,
    isSticky: false,
    ratingsNumber: 540,
    ratingsTotal: 2478,
    moderatorNotes: "",
    isDraft: false,
    isApproved: true,
    unapprovedPostsTotal: 0,
    attachmentTotal: 0,
    isDeleted: false,
  },
  {
    id: 10,
    forumId: 2,
    subject: "Single Topic",
    prefix: "",
    icon: "",
    pollId: null,
    userId: "uuid",
    username: "Elegant Totality",
    createdAt: new Date(),
    updatedAt: new Date(),
    firstPostId: 1,
    lastPostCreatedAt: new Date(),
    lastPosterUsername: "Elegant Totality",
    lastPosterId: "uuid",
    views: 100,
    replies: 35,
    isClosed: false,
    isSticky: false,
    ratingsNumber: 540,
    ratingsTotal: 2478,
    moderatorNotes: "",
    isDraft: false,
    isApproved: true,
    unapprovedPostsTotal: 0,
    attachmentTotal: 0,
    isDeleted: false,
  },
];

export class ThreadService {
  constructor(baseUrl: string) {}

  getLastNThreadsInForum(forumId: number, _n: number): Thread[] {
    const allThreads = threads.filter((thread) => thread.forumId === forumId);
    return allThreads;
  }

  getThreadById(threadId: number): Thread | undefined {
    const thread = threads.find((th) => th.id === threadId);
    return thread;
  }
}
