import { forumSchema as forums } from "../schema";
import { PgTransaction } from "drizzle-orm/pg-core";
import { NodePgQueryResultHKT } from "drizzle-orm/node-postgres";
import { ExtractTablesWithRelations } from "drizzle-orm";

/**
 * Seeds the default forums.
 *
 * Rules:
 * - Must be idempotent
 * - Must not assume any existing data
 * - Must not delete or mutate user-created records
 */
export async function seedForums(
  db: PgTransaction<
    NodePgQueryResultHKT,
    Record<string, unknown>,
    ExtractTablesWithRelations<Record<string, unknown>>
  >,
) {
  // 1. Check if a forum already exists
  const existing = await db.select({ id: forums.id }).from(forums).limit(1);

  if (existing.length > 0) {
    // Forum already exists; do nothing
    return;
  }

  forumData.map(async (forum) => {
    // 2. Insert default forums
    await db.insert(forums).values({
      isCategory: forum.isCategory,
      parentForumId: forum.parentForumId,
      name: forum.name,
      description: forum.description,
      linkTo: forum.linkTo,
      password: forum.password,
      displayOrder: forum.displayOrder,
      threadCount: forum.threadCount,
      postCount: forum.postCount,
      lastPostTime: forum.lastPostTime.toISOString(),
      lastPostAuthor: forum.lastPostAuthor,
      lastPostThreadId: forum.lastPostThreadId,
      lastPostThreadSubject: forum.lastPostThreadSubject,
      rulesTitle: forum.rulesTitle,
      rules: forum.rules,
      unapprovedThreadCount: forum.unapprovedThreadCount,
      unapprovedPostCount: forum.unapprovedPostCount,
      isActive: forum.isActive,
      isLocked: forum.isLocked,
      allowRatings: forum.allowRatings,
      usePostCounts: forum.usePostCounts,
      mustReviewPosts: forum.mustReviewPosts,
      mustReviewThreads: forum.mustReviewThreads,
      mustReviewAttachments: forum.mustReviewAttachments,
      canModsEdit: forum.canModsEdit,
    });
  });
}

const forumData = [
  {
    id: 1,
    isCategory: true,
    parentForumId: null,
    name: "Category One",
    description: "The first category",
    linkTo: null,
    password: null,
    displayOrder: 0,
    threadCount: 1,
    postCount: 10,
    lastPostTime: new Date(),
    lastPostAuthor: "uuid", // user ID
    lastPostThreadId: 1,
    lastPostThreadSubject: "Latest Thread Subject",
    rulesTitle: "Category Rules",
    rules: "Rules go here.",
    unapprovedThreadCount: 6,
    unapprovedPostCount: 15,
    isActive: true,
    isLocked: false,
    allowRatings: true,
    usePostCounts: true,
    mustReviewPosts: false,
    mustReviewThreads: false,
    mustReviewAttachments: false,
    canModsEdit: true,
  },
  {
    id: 2,
    isCategory: false,
    parentForumId: 1,
    name: "Forum One",
    description: "The first forum",
    linkTo: null,
    password: null,
    displayOrder: 0,
    threadCount: 1,
    postCount: 10,
    lastPostTime: new Date(),
    lastPostAuthor: "uuid", // user ID
    lastPostThreadId: 1,
    lastPostThreadSubject: "Latest Thread Subject",
    rulesTitle: "Forum One Rules",
    rules: "Rules go here.",
    unapprovedThreadCount: 6,
    unapprovedPostCount: 15,
    isActive: true,
    isLocked: false,
    allowRatings: true,
    usePostCounts: true,
    mustReviewPosts: false,
    mustReviewThreads: false,
    mustReviewAttachments: false,
    canModsEdit: true,
  },
  {
    id: 3,
    isCategory: false,
    parentForumId: 1,
    name: "Forum Two",
    description: "The second forum",
    linkTo: null,
    password: null,
    displayOrder: 0,
    threadCount: 15,
    postCount: 130,
    lastPostTime: new Date(),
    lastPostAuthor: "uuid", // user ID
    lastPostThreadId: 1,
    lastPostThreadSubject: "Latest Thread Subject",
    rulesTitle: "Forum Two Rules",
    rules: "Rules go here.",
    unapprovedThreadCount: 6,
    unapprovedPostCount: 15,
    isActive: true,
    isLocked: true,
    allowRatings: true,
    usePostCounts: true,
    mustReviewPosts: false,
    mustReviewThreads: false,
    mustReviewAttachments: false,
    canModsEdit: true,
  },
  {
    id: 4,
    isCategory: false,
    parentForumId: 3,
    name: "Child Forum One",
    description: "The first child forum",
    linkTo: null,
    password: null,
    displayOrder: 0,
    threadCount: 15,
    postCount: 130,
    lastPostTime: new Date(),
    lastPostAuthor: "uuid", // user ID
    lastPostThreadId: 1,
    lastPostThreadSubject: "Latest Thread Subject",
    rulesTitle: "Forum Two Rules",
    rules: "Rules go here.",
    unapprovedThreadCount: 6,
    unapprovedPostCount: 15,
    isActive: true,
    isLocked: true,
    allowRatings: true,
    usePostCounts: true,
    mustReviewPosts: false,
    mustReviewThreads: false,
    mustReviewAttachments: false,
    canModsEdit: true,
  },
  {
    id: 5,
    isCategory: false,
    parentForumId: 3,
    name: "Child Forum Two",
    description: "The second child forum",
    linkTo: null,
    password: null,
    displayOrder: 0,
    threadCount: 15,
    postCount: 130,
    lastPostTime: new Date(),
    lastPostAuthor: "uuid", // user ID
    lastPostThreadId: 1,
    lastPostThreadSubject: "Latest Thread Subject",
    rulesTitle: "Forum Two Rules",
    rules: "Rules go here.",
    unapprovedThreadCount: 6,
    unapprovedPostCount: 15,
    isActive: true,
    isLocked: false,
    allowRatings: true,
    usePostCounts: true,
    mustReviewPosts: false,
    mustReviewThreads: false,
    mustReviewAttachments: false,
    canModsEdit: true,
  },
  {
    id: 6,
    isCategory: false,
    parentForumId: 3,
    name: "Child Forum Three",
    description: "The third child forum",
    linkTo: null,
    password: null,
    displayOrder: 0,
    threadCount: 15,
    postCount: 130,
    lastPostTime: new Date(),
    lastPostAuthor: "uuid", // user ID
    lastPostThreadId: 1,
    lastPostThreadSubject: "Latest Thread Subject",
    rulesTitle: "Forum Two Rules",
    rules: "Rules go here.",
    unapprovedThreadCount: 6,
    unapprovedPostCount: 15,
    isActive: true,
    isLocked: false,
    allowRatings: true,
    usePostCounts: true,
    mustReviewPosts: false,
    mustReviewThreads: false,
    mustReviewAttachments: false,
    canModsEdit: true,
  },
  {
    id: 7,
    isCategory: false,
    parentForumId: 3,
    name: "Child Forum Four",
    description: "The fourth child forum",
    linkTo: null,
    password: null,
    displayOrder: 0,
    threadCount: 15,
    postCount: 130,
    lastPostTime: new Date(),
    lastPostAuthor: "uuid", // user ID
    lastPostThreadId: 1,
    lastPostThreadSubject: "Latest Thread Subject",
    rulesTitle: "Forum Two Rules",
    rules: "Rules go here.",
    unapprovedThreadCount: 6,
    unapprovedPostCount: 15,
    isActive: true,
    isLocked: false,
    allowRatings: true,
    usePostCounts: true,
    mustReviewPosts: false,
    mustReviewThreads: false,
    mustReviewAttachments: false,
    canModsEdit: true,
  },
];
