import { Forum, ForumRepository, Forums } from "@reactforums/core";

export function drizzleAdapter() {
  const forumRepo = new DrizzleForumRepository();

  const repositories = {
    // ban: DrizzleBanRepository,
    // category: DrizzleCategoryRepository,
    forum: forumRepo,
    // message: DrizzleMessageRepository,
    // notification: DrizzleNotificationRepository,
    // post: DrizzlePostRepository,
    // report: DrizzleReportRepository,
    // session: DrizzleSessionRepository,
    // thread: DrizzleThreadRepository,
    // user: DrizzleUserRepository,
  };

  return repositories;
}

class DrizzleForumRepository implements ForumRepository {
  async getAllForums(): Promise<Forums> {
    return forums;
  }

  async getForumById(id: number): Promise<Forum | undefined> {
    return forums.find((f) => f.id === id);
  }
}

const forums = [
  {
    id: 1,
    isCategory: true,
    parentForumId: null,
    name: "Category One",
    description: "The first category",
    linkTo: null,
    password: null,
    displayOrder: 0,
    threadCount: 1,
    postCount: 10,
    lastPostTime: new Date(),
    lastPostAuthor: "uuid", // user ID
    lastPostThreadId: 1,
    lastPostThreadSubject: "Latest Thread Subject",
    rulesTitle: "Category Rules",
    rules: "Rules go here.",
    unapprovedThreadCount: 6,
    unapprovedPostCount: 15,
    isActive: true,
    isLocked: false,
    allowRatings: true,
    usePostCounts: true,
    mustReviewPosts: false,
    mustReviewThreads: false,
    mustReviewAttachments: false,
    canModsEdit: true,
  },
  {
    id: 2,
    isCategory: false,
    parentForumId: 1,
    name: "Forum One",
    description: "The first forum",
    linkTo: null,
    password: null,
    displayOrder: 0,
    threadCount: 1,
    postCount: 10,
    lastPostTime: new Date(),
    lastPostAuthor: "uuid", // user ID
    lastPostThreadId: 1,
    lastPostThreadSubject: "Latest Thread Subject",
    rulesTitle: "Forum One Rules",
    rules: "Rules go here.",
    unapprovedThreadCount: 6,
    unapprovedPostCount: 15,
    isActive: true,
    isLocked: false,
    allowRatings: true,
    usePostCounts: true,
    mustReviewPosts: false,
    mustReviewThreads: false,
    mustReviewAttachments: false,
    canModsEdit: true,
  },
  {
    id: 3,
    isCategory: false,
    parentForumId: 1,
    name: "Forum Two",
    description: "The second forum",
    linkTo: null,
    password: null,
    displayOrder: 0,
    threadCount: 15,
    postCount: 130,
    lastPostTime: new Date(),
    lastPostAuthor: "uuid", // user ID
    lastPostThreadId: 1,
    lastPostThreadSubject: "Latest Thread Subject",
    rulesTitle: "Forum Two Rules",
    rules: "Rules go here.",
    unapprovedThreadCount: 6,
    unapprovedPostCount: 15,
    isActive: true,
    isLocked: true,
    allowRatings: true,
    usePostCounts: true,
    mustReviewPosts: false,
    mustReviewThreads: false,
    mustReviewAttachments: false,
    canModsEdit: true,
  },
  {
    id: 4,
    isCategory: false,
    parentForumId: 3,
    name: "Child Forum One",
    description: "The first child forum",
    linkTo: null,
    password: null,
    displayOrder: 0,
    threadCount: 15,
    postCount: 130,
    lastPostTime: new Date(),
    lastPostAuthor: "uuid", // user ID
    lastPostThreadId: 1,
    lastPostThreadSubject: "Latest Thread Subject",
    rulesTitle: "Forum Two Rules",
    rules: "Rules go here.",
    unapprovedThreadCount: 6,
    unapprovedPostCount: 15,
    isActive: true,
    isLocked: true,
    allowRatings: true,
    usePostCounts: true,
    mustReviewPosts: false,
    mustReviewThreads: false,
    mustReviewAttachments: false,
    canModsEdit: true,
  },
  {
    id: 5,
    isCategory: false,
    parentForumId: 3,
    name: "Child Forum Two",
    description: "The second child forum",
    linkTo: null,
    password: null,
    displayOrder: 0,
    threadCount: 15,
    postCount: 130,
    lastPostTime: new Date(),
    lastPostAuthor: "uuid", // user ID
    lastPostThreadId: 1,
    lastPostThreadSubject: "Latest Thread Subject",
    rulesTitle: "Forum Two Rules",
    rules: "Rules go here.",
    unapprovedThreadCount: 6,
    unapprovedPostCount: 15,
    isActive: true,
    isLocked: false,
    allowRatings: true,
    usePostCounts: true,
    mustReviewPosts: false,
    mustReviewThreads: false,
    mustReviewAttachments: false,
    canModsEdit: true,
  },
  {
    id: 6,
    isCategory: false,
    parentForumId: 3,
    name: "Child Forum Three",
    description: "The third child forum",
    linkTo: null,
    password: null,
    displayOrder: 0,
    threadCount: 15,
    postCount: 130,
    lastPostTime: new Date(),
    lastPostAuthor: "uuid", // user ID
    lastPostThreadId: 1,
    lastPostThreadSubject: "Latest Thread Subject",
    rulesTitle: "Forum Two Rules",
    rules: "Rules go here.",
    unapprovedThreadCount: 6,
    unapprovedPostCount: 15,
    isActive: true,
    isLocked: false,
    allowRatings: true,
    usePostCounts: true,
    mustReviewPosts: false,
    mustReviewThreads: false,
    mustReviewAttachments: false,
    canModsEdit: true,
  },
  {
    id: 7,
    isCategory: false,
    parentForumId: 3,
    name: "Child Forum Four",
    description: "The fourth child forum",
    linkTo: null,
    password: null,
    displayOrder: 0,
    threadCount: 15,
    postCount: 130,
    lastPostTime: new Date(),
    lastPostAuthor: "uuid", // user ID
    lastPostThreadId: 1,
    lastPostThreadSubject: "Latest Thread Subject",
    rulesTitle: "Forum Two Rules",
    rules: "Rules go here.",
    unapprovedThreadCount: 6,
    unapprovedPostCount: 15,
    isActive: true,
    isLocked: false,
    allowRatings: true,
    usePostCounts: true,
    mustReviewPosts: false,
    mustReviewThreads: false,
    mustReviewAttachments: false,
    canModsEdit: true,
  },
];
